status: dont traceback if there are no releases
latest_release can be None which results in

    AttributeError: 'NoneType' object has no attribute 'title'

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>